name: Demo Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "* 15 * * *"

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hej BMW 🚙"
  list-files:
    runs-on: ubuntu-latest
    needs: demo
    steps:
      - uses: actions/checkout@v4
      - run: ls -l
